#ifndef VIRGIL_MBEDTLS_CONFIG_PNACL_H
#define VIRGIL_MBEDTLS_CONFIG_PNACL_H

#define MBEDTLS_NO_PLATFORM_ENTROPY
#define MBEDTLS_TIMING_C
#define MBEDTLS_HAVEGE_C

#endif // VIRGIL_MBEDTLS_CONFIG_PNACL_H
